pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!' 
                echo ' hello mehdi how are you , learn with sagar '
                echo 'Hello world!'
                echo ' df -h'
                echo ' mehdi al mehdi'
                echo ' again testing the jenkin'
                echo 'Triggering jenkins pipeline 2'
            }
        }
    }
}
