pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!' 
                echo ' hello mehdi how are you , learn with sagar '

                echo ' imran bhai testing'
                echo ' learnwithsagar jenkins'

                echo ' getfitwithsagar jenkins'
                
                
            }
        }
    }
}
