pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!' 
                echo ' hello mehdi how are you , learn with sagar '
                echo ' javed ali khan ************'
                echo '&&& n ************'
                
                

                echo ' Welcome'
               
                
                
            }
        }
    }
}
